"""initial_webshop

Revision ID: ee41826e747a
Revises: 
Create Date: 2026-04-04 10:35:54.482231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee41826e747a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_naam', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('user_input', sa.Text(), nullable=False),
    sa.Column('agent_output', sa.Text(), nullable=False),
    sa.Column('prompt_versie', sa.String(length=10), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('verwerkingstijd_ms', sa.Integer(), nullable=True),
    sa.Column('aangemaakt_op', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('naam', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('omschrijving', sa.Text(), nullable=True),
    sa.Column('aangemaakt_op', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('naam'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('naam', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('telefoon', sa.String(length=20), nullable=True),
    sa.Column('straat', sa.String(length=200), nullable=True),
    sa.Column('postcode', sa.String(length=10), nullable=True),
    sa.Column('stad', sa.String(length=100), nullable=True),
    sa.Column('land', sa.String(length=2), nullable=False),
    sa.Column('aangemaakt_op', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('naam', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('wachtwoord_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'klant', 'tester', name='userrole'), nullable=False),
    sa.Column('actief', sa.Boolean(), nullable=False),
    sa.Column('aangemaakt_op', sa.DateTime(timezone=True), nullable=False),
    sa.Column('laatste_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_nummer', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'processing', 'shipped', 'delivered', 'returned', 'cancelled', name='orderstatus'), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('totaal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('btw_bedrag', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('verzendkosten', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('betaalmethode', sa.String(length=50), nullable=True),
    sa.Column('payment_id', sa.String(length=100), nullable=True),
    sa.Column('tracking_code', sa.String(length=100), nullable=True),
    sa.Column('notities', sa.Text(), nullable=True),
    sa.Column('aangemaakt_op', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bijgewerkt_op', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_nummer')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('naam', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('korte_beschrijving', sa.String(length=500), nullable=True),
    sa.Column('beschrijving', sa.Text(), nullable=True),
    sa.Column('seo_titel', sa.String(length=70), nullable=True),
    sa.Column('seo_omschrijving', sa.String(length=160), nullable=True),
    sa.Column('prijs', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('voorraad', sa.Integer(), nullable=False),
    sa.Column('laag_voorraad_drempel', sa.Integer(), nullable=False),
    sa.Column('afbeelding_url', sa.String(length=500), nullable=True),
    sa.Column('extra_afbeeldingen', sa.JSON(), nullable=True),
    sa.Column('kenmerken', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('actief', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('aangemaakt_op', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bijgewerkt_op', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('factuur_nummer', sa.String(length=20), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('totaal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('btw_bedrag', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('aangemaakt_op', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factuur_nummer'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('aantal', sa.Integer(), nullable=False),
    sa.Column('stukprijs', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotaal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('invoices')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('users')
    op.drop_table('customers')
    op.drop_table('categories')
    op.drop_table('agent_logs')
    # ### end Alembic commands ###
